# CREDIT: https://github.com/shren207/nextjs-docker-compose
# Dockerfile
FROM node:16-buster

RUN apt update
RUN apt install -qyy entr wget curl moreutils

RUN mkdir -p /app/node_modules
# COPY --chown=1000 . /app
# RUN chown 1000:1000 -R /app

# Run the image.
# CMD npm start --silent

# RUN npm i -g blitz@latest
