services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5555:5555
    working_dir: /app
    volumes:
      - $PWD:/app
      - node_modules:/app/node_modules

    command: sleep infinity

volumes:
  node_modules:
